#!/bin/bash

# it should be fixed

# workaround when .indy become regular file
if [ -f /home/${SUDO_USER}/.indy ]; then
    rm /home/${SUDO_USER}/.indy
fi
mkdir -p /home/${SUDO_USER}/.indy
cp -nr /usr/local/lib/python3.5/dist-packages/sovrin/pool_transactions_local_genesis /home/${SUDO_USER}/.indy 2>/dev/null
cp -nr /usr/local/lib/python3.5/dist-packages/sovrin/pool_transactions_sandbox_genesis /home/${SUDO_USER}/.indy 2>/dev/null
cp -nr /usr/local/lib/python3.5/dist-packages/sovrin/pool_transactions_live_genesis /home/${SUDO_USER}/.indy 2>/dev/null

chown -R ${SUDO_USER}:${SUDO_USER} /home/${SUDO_USER}/.indy

# workaround when .indy become regular file
if [ -f /home/indy/.indy ]; then
    rm /home/indy/.indy
fi
mkdir -p /home/indy/.indy

cp -nr /usr/local/lib/python3.5/dist-packages/sovrin/domain_transactions_local_genesis /home/indy/.indy 2>/dev/null
cp -nr /usr/local/lib/python3.5/dist-packages/sovrin/domain_transactions_sandbox_genesis /home/indy/.indy 2>/dev/null
cp -nr /usr/local/lib/python3.5/dist-packages/sovrin/domain_transactions_live_genesis /home/indy/.indy 2>/dev/null
cp -nr /usr/local/lib/python3.5/dist-packages/sovrin/pool_transactions_local_genesis /home/indy/.indy 2>/dev/null
cp -nr /usr/local/lib/python3.5/dist-packages/sovrin/pool_transactions_sandbox_genesis /home/indy/.indy 2>/dev/null
cp -nr /usr/local/lib/python3.5/dist-packages/sovrin/pool_transactions_live_genesis /home/indy/.indy 2>/dev/null

chown -R indy:indy /home/indy/.indy

# adding sovrin package to packages to hold
SOVRIN_IS_HELD=$(grep HOLD_EXT=.*sovrin.* /etc/sovrin/node_control.conf)
if [ -z "${SOVRIN_IS_HELD}" ]; then
    sed -ie 's|HOLD_EXT=\\"\(.*\)|HOLD_EXT=\\"sovrin \1|' /etc/sovrin/node_control.conf
fi

# Automatically added from template:
if which py3compile >/dev/null 2>&1; then
	py3compile -O -p sovrin /usr/local/lib/python3.5/dist-packages/
fi

# End automatically added section
