#!/bin/bash

# it should be fixed
USER_CONFIG_DIR="/etc/indy"
GENERAL_DATA_DIR="/var/lib/indy"
GENERAL_LOG_DIR="/var/log/indy"

CLI_BASE_DIR="/home/$SUDO_USER/.indy-cli"
CLI_NETWORKS_DIR="$CLI_BASE_DIR/networks"
CLI_WALLETS_DIR="$CLI_BASE_DIR/wallets"

INSTALL_DIR="/usr/local/lib/python3.5/dist-packages"


LOCAL_NETWORK='local'
SANDBOX_NETWORK='sandbox'
LIVE_NETWORK='live'
DEFAULT_NETWORK=$SANDBOX_NETWORK


if [ ! -d $USER_CONFIG_DIR ]; then
    echo "Could not find indy node user config dir '$USER_CONFIG_DIR', terminating"
    exit 1
fi

if [ ! -f $USER_CONFIG_DIR/indy_config.py ]; then
    echo "Could not find indy node config '$USER_CONFIG_DIR/indy_config.py', terminating"
    exit 1
fi

if [ ! -d $CLI_BASE_DIR ]; then
    echo "Could not find indy CLI base dir '$CLI_BASE_DIR', terminating"
    exit 1
fi

if [ ! -f $CLI_BASE_DIR/indy_config.py ]; then
    echo "Could not find indy CLI config '$CLI_BASE_DIR/indy_config.py', terminating"
    exit 1
fi

#################### CLI part ####################
for network in $LOCAL_NETWORK $SANDBOX_NETWORK $LIVE_NETWORK
do
    mkdir -p $CLI_NETWORKS_DIR/$network $CLI_NETWORKS_DIR/$network/data $CLI_WALLETS_DIR/$network
    cp -nr $INSTALL_DIR/sovrin/pool_transactions_${network}_genesis \
        $CLI_NETWORKS_DIR/$network/pool_transactions_genesis 2>/dev/null
done
chown -R ${SUDO_USER}:${SUDO_USER} $CLI_BASE_DIR

# Set default network in indy config file
sed -i "s/^\(CURRENT_NETWORK\s*=\s*\).*\$/\1\"$DEFAULT_NETWORK\"/" "$CLI_BASE_DIR/indy_config.py"

#################### Service part ####################
for network in $LOCAL_NETWORK $SANDBOX_NETWORK $LIVE_NETWORK
do
    mkdir -p $GENERAL_DATA_DIR/$network $GENERAL_DATA_DIR/$network/data $GENERAL_LOG_DIR/$network

    cp -nr $INSTALL_DIR/sovrin/domain_transactions_${network}_genesis \
        $GENERAL_DATA_DIR/$network/domain_transactions_genesis 2>/dev/null
    cp -nr $INSTALL_DIR/sovrin/pool_transactions_${network}_genesis \
        $GENERAL_DATA_DIR/$network/pool_transactions_genesis 2>/dev/null

    chown -R indy:indy $GENERAL_DATA_DIR/$network $GENERAL_LOG_DIR/$network
done

# Set default network in indy config file
sed -i "s/^\(CURRENT_NETWORK\s*=\s*\).*\$/\1\"$DEFAULT_NETWORK\"/" "$USER_CONFIG_DIR/indy_config.py"

# adding sovrin package to packages to hold
SOVRIN_IS_HELD=$(grep HOLD_EXT=.*sovrin.* /etc/sovrin/node_control.conf)
if [ -z "${SOVRIN_IS_HELD}" ]; then
    sed -ie 's|HOLD_EXT=\\"\(.*\)|HOLD_EXT=\\"sovrin \1|' /etc/sovrin/node_control.conf
fi

# Automatically added from template:
if which py3compile >/dev/null 2>&1; then
	py3compile -O -p sovrin $INSTALL_DIR
fi

# End automatically added section
